In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
a=np.arange(10)
print(a)  # arange is used to  print sequential order 

[0 1 2 3 4 5 6 7 8 9]


In [4]:
l=range(100)
%timeit [i**2 for i in l]

4.35 µs ± 61 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
a=np.arange(100)
%timeit a**2

472 ns ± 8.11 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# creating array

In [6]:
#one dimensinal array
a=np.array([1,2,3,4])

In [19]:
print(a.ndim)  # to know the dimesnsion of array

1


In [10]:
#two dimesional array
b=np.array([[1,2,3],[4,5,6]])

In [11]:
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
print(b.ndim)

2


In [24]:
#three dimesional array
c=np.array([[[1,2],[3,4],[5,6]]])

In [25]:
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [26]:
print(c.ndim)

3


In [27]:
print(a.shape)

(4,)


In [28]:
print(b.shape)

(2, 3)


In [30]:
print(c.shape) #to know the rows and columns in array

(1, 3, 2)


# basic functions of array

In [31]:
#using linspace
a=np.linspace(0,1,6)  # 0-1 madhayalo 6 values print chestundhi
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [32]:
#ones
a=np.ones((3,3))  # to used to print  one for no of rows and   columns . here 3,3 is size of array i.e is 3 rows and 3 columms
print(a)  # size of array should mention in tuple i.e (3,3)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
#zeros
a=np.zeros((4,4))  # same as ones but print zeros
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
#eye
a=np.eye(3)
print(a)       # print 1 as diagonals here 3 is the rows and coulmns vale

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [38]:
#diag  
a=np.diag([1,2,3,4])   # to print values like 1,2,3,4 in daigonally
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [39]:
print(np.diag(a))    # to print the daigonal values of array  a

[1 2 3 4]


# basic datatypes

In [40]:
# to check the type of array dtype is used
a=np.arange(10)
print(a.dtype)

int32


In [41]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


In [45]:
a=np.arange(10,dtype="float")
print(a.dtype)

float64


In [44]:
a=np.zeros((4,4))
print(a)
print(a.dtype)  # it is flaot because it is 0. so it is float

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [46]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [47]:
a=np.array([True,False])
print(a.dtype)

bool


In [48]:
a=np.array(["neelima","aditya degree college"])
print(a.dtype)    # u21 because max length of string  is 21 ie is aditya degree college

<U21


# indexing and slicing

In [49]:
a=np.arange(10)
print(a[5])

5


In [50]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [53]:
a=np.diag([1,2,3])
print(a[0,1])

0


In [54]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# slicing

In [56]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
print(a[1:7:2])

[1 3 5]


In [59]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# copies and viewing

In [60]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [61]:
print(np.shares_memory(a,b))

True


In [62]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [63]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [64]:
print(np.shares_memory(a,b))

False


In [65]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# random number generator

In [66]:
a=np.random.randint(0,20,15)
print(a)

[ 0 14  0 15  4  8  8  6  8 13  3  1  7  4  9]


In [67]:
mask=(a%2==0)

In [68]:
mask_a=a[mask]
print(mask_a)

[ 0 14  0  4  8  8  6  8  4]


In [69]:
a[mask]=-1
print(a)

[-1 -1 -1 15 -1 -1 -1 -1 -1 13  3  1  7 -1  9]
